<?php 
$translate = [
  'ru' => [
    'main' => 'Главная',
    'news' => 'Новости',
    'currentNews' => 'Текущие новости',
    'aboutAgency' => 'Об агентстве',
    'leadership' => 'Руководство',
    'services' => 'Услуги',
    'partners' => 'Партнеры',
    'logistics' => 'Логистика',
    'logisticsCompanies' => 'Логистические компании',
    'logisticPortal' => 'Логистический портал',
    'registers' => 'Реестры',
    'ERAP' => 'Реестры экспортируемой сельскохозяйственной продукции',
    'EIPR' => 'Реестры экспортируемой промышленной продукции',
    'exportGuide' => 'Путеводитель по экспорту',
    'NDS' => 'Национальная стратегия развития',
    'regulations' => 'Нормативно правовые акты',
    'TPT' => 'Торговый портал Таджикистана',
    'sourcesInformation' => 'Источники информации по ВЭД',
    'tradingCard' => 'Торговая карта',
    'marketAnalysis' => 'Анализ рынка',
    'WTO' => 'Всемирная торговая организация',
    'TTAC' => 'Торговый Оборот Всех Стран',
    'activity' => 'Мероприятия',
    'contacts' => 'Контакты',
    'lang' => 'Русский',
    'reception' => 'Приёмная',
    'commonDepartment' => 'Общий отдел',
    'fax' => 'Факс',
    'exchangeRate' => 'Курс валют',
    'siteTitle' => 'Агентство по экспорту при Правительстве Республики Таджикистан',
    'weeks' => '<td>Пн</td><td>Вт</td><td>Ср</td><td>Чт</td><td>Пт</td><td>Сб</td><td>Вс</td>'
  ],
  'en' => [
    'main' => 'Main',
    'news' => 'News',
    'currentNews' => 'Current news',
    'aboutAgency' => 'About agency',
    'leadership' => 'Leadership',
    'services' => 'Services',
    'partners' => 'Partners',
    'logistics' => 'Logistics',
    'logisticsCompanies' => 'Logistics companies',
    'logisticPortal' => 'Logistic portal',
    'registers' => 'Registers',
    'ERAP' => 'Export registers of agricultural products',
    'EIPR' => 'Exported industrial product registers',
    'exportGuide' => 'Export guide',
    'NDS' => 'National development strategy',
    'regulations' => 'Regulations',
    'TPT' => 'Trade portal of Tajikistan',
    'sourcesInformation' => 'Sources information',
    'tradingCard' => 'Trading card',
    'marketAnalysis' => 'Market analysis',
    'WTO' => 'World trade organisation',
    'TTAC' => 'Trade Turnover of All Countries',
    'activity' => 'Activity',
    'contacts' => 'Сontacts',
    'lang' => 'English',
    'reception' => 'Reception',
    'commonDepartment' => 'Common department',
    'fax' => 'Fax',
    'exchangeRate' => 'Exchange rate',
    'siteTitle' => 'Export for agency under the Government of the Republic of Tajikistan',
    'weeks' => '<td>Mo</td><td>Tu</td><td>We</td><td>Th</td><td>Fr</td><td>Sa</td><td>Su</td>'
  ],
  'tj' => [
    'main' => 'Асосӣ',
    'news' => 'Хабарҳо',
    'currentNews' => 'Ахбори ҷорӣ',
    'aboutAgency' => 'Дар бораи Агентӣ',
    'leadership' => 'Роҳбарият',
    'services' => 'Хизматрасониҳо',
    'partners' => 'Шарикон',
    'logistics' => 'Логистика',
    'logisticsCompanies' => 'Ширкатҳои логистикӣ',
    'logisticPortal' => 'Портали лгистикӣ',
    'registers' => 'Феҳристҳо',
    'ERAP' => 'Феҳристи кишоварзӣ',
    'EIPR' => 'Феҳристи саноатӣ',
    'exportGuide' => 'Роҳнамои содирот',
    'NDS' => 'Стратегияи миллии рушд',
    'regulations' => 'Санадҳои меъёрии ҳуқуқӣ',
    'TPT' => 'Портали савдои Тоҷикистон',
    'sourcesInformation' => 'Манбаъҳои иттилоот оид ба ФИХ',
    'tradingCard' => 'Харитаи тиҷоратӣ',
    'marketAnalysis' => 'Таҳлили бозор',
    'WTO' => 'Созмони умумӣ ҷаҳонии савдо',
    'TTAC' => 'Гардиши моли ҳамаи давлатҳо',
    'activity' => 'Чорабиниҳо',
    'contacts' => 'Тамос',
    'lang' => 'Тоҷикӣ',
    'reception' => 'Қабулгоҳ',
    'commonDepartment' => 'Шубаи умумӣ',
    'fax' => 'Факс',
    'exchangeRate' => 'Қурби асъор',
    'siteTitle' => 'Агентии содиротии назди Ҳукумати Ҷумҳурии Тоҷикистон',
    'weeks' => '<td>Пн</td><td>Вт</td><td>Ср</td><td>Чт</td><td>Пт</td><td>Сб</td><td>Вс</td>'
  ]
];

$main = $translate[$currentLang]['main'];
$news = $translate[$currentLang]['news'];
$currentNews = $translate[$currentLang]['currentNews'];
$aboutAgency = $translate[$currentLang]['aboutAgency'];
$leadership = $translate[$currentLang]['leadership'];
$services = $translate[$currentLang]['services'];
$partners = $translate[$currentLang]['partners'];
$logistics = $translate[$currentLang]['logistics'];
$logisticsCompanies = $translate[$currentLang]['logisticsCompanies'];
$logisticPortal = $translate[$currentLang]['logisticPortal'];
$registers = $translate[$currentLang]['registers'];
$ERAP = $translate[$currentLang]['ERAP'];
$EIPR = $translate[$currentLang]['EIPR'];
$exportGuide = $translate[$currentLang]['exportGuide'];
$NDS = $translate[$currentLang]['NDS'];
$regulations = $translate[$currentLang]['regulations'];
$TPT = $translate[$currentLang]['TPT'];
$sourcesInformation = $translate[$currentLang]['sourcesInformation'];
$tradingCard = $translate[$currentLang]['tradingCard'];
$marketAnalysis = $translate[$currentLang]['marketAnalysis'];
$WTO = $translate[$currentLang]['WTO'];
$TTAC = $translate[$currentLang]['TTAC'];
$activity = $translate[$currentLang]['activity'];
$contacts = $translate[$currentLang]['contacts'];
$langText = $translate[$currentLang]['lang'];

$reception = $translate[$currentLang]['reception'];
$commonDepartment = $translate[$currentLang]['commonDepartment'];
$fax = $translate[$currentLang]['fax'];
$exchangeRate = $translate[$currentLang]['exchangeRate'];
$siteTitle = $translate[$currentLang]['siteTitle'];
$weeks = $translate[$currentLang]['weeks'];

?>